development:
  adapter: postgresql
  encoding: utf8
  database: lucybloomfield
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: luchia_test
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST